// Generated by CoffeeScript 1.4.0

module.exports = {
  validate: function(object, meta) {
    return true;
  },
  filter: function(object, meta, callback) {
    return callback(null, {
      example: true
    });
  }
};
