// Generated by CoffeeScript 1.3.3
var URL, cheerio, fetchGoogleDescriptions, invoke;

URL = require('url');

invoke = require('ouija');

cheerio = require('cheerio');

fetchGoogleDescriptions = function(url, callback) {
  var hostname, resultsurl;
  hostname = encodeURIComponent(URL.parse(url).hostname);
  resultsurl = "https://www.google.ca/search?q=" + hostname + "&oq=site:" + hostname + "&cad=h";
  return invoke(resultsurl, ['html'], function(error, html) {
    var $, texts;
    try {
      $ = cheerio.load(html);
      texts = $('li.g .st').map(function() {
        return $(this).text();
      });
    } catch (error) {
      return callback(error);
    }
    return callback(null, {
      google_descriptions: texts
    });
  });
};

module.exports = {
  validate: function(object, meta) {
    return object.website_url;
  },
  filter: function(object, meta, callback) {
    return fetchGoogleDescriptions(object.website_url, callback);
  }
};
