// Generated by CoffeeScript 1.4.0

module.exports = {
  validate: function(object, meta, callback) {
    return meta.website_scrape && meta.website_scrape.html;
  },
  filter: function(object, meta, callback) {
    var html, twurls, unique;
    html = meta.website_scrape.html;
    twurls = html.match(/https?\:\/\/twitter\.com(\/\#\!)?\/([^\"\']+)/g);
    if (!twurls) {
      return callback();
    }
    unique = twurls.reduce(function(uniq, url) {
      url = url.toLowerCase().replace(/https/, 'http');
      if (uniq.indexOf(url) === -1) {
        uniq.push(url);
      }
      return uniq;
    }, []);
    return callback(null, {
      website_twitter: unique
    });
  }
};
