// Generated by CoffeeScript 1.4.0
var invoke;

invoke = require('ouija');

module.exports = {
  validate: function(object, meta) {
    return object.website_url;
  },
  filter: function(object, meta, callback) {
    var answered, website_scrape;
    answered = 0;
    website_scrape = {};
    invoke(object.website_url, ['html'], function(error, html) {
      answered++;
      website_scrape.html = html;
      if (answered === 2) {
        return callback(null, {
          website_scrape: website_scrape
        });
      }
    });
    return invoke(object.website_url, ['screen'], function(error, blob) {
      answered++;
      website_scrape.screenshot = blob;
      if (answered === 2) {
        return callback(null, {
          website_scrape: website_scrape
        });
      }
    });
  }
};
